# -*- coding: utf-8 -*-
"""vis_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S8Gjjrokl99__Z0I3Q-QYJdI6HvSJyCU
"""

#!pip install plotly_express

#!pip install dash_bootstrap_components

# import plotly_express as px
import pandas as pd
import plotly.graph_objs as go


#导入全国每月销售额数据
df = pd.read_csv("../dataset/monthly/total_sale_monthly_noaccu.csv")
df.head(10)
#去掉含有空值的数据行
df.dropna(axis='index',how='any',inplace=True)
df.head()

#画销售额折线图
def paint_fig_ts(years=['2019','2020','2021','2022']):
  #分别筛选出每年的数据
  for y in years:
    df_CB=df[df['Building Type'].isin(['Commercialized Buildings Sold'])&df['Date'].str.contains('|'.join(years))]
    df_CRB=df[df['Building Type'].isin(['Commercialized Residential Buildings Sold'])&df['Date'].str.contains('|'.join(years))]
    df_OB=df[df['Building Type'].isin(['Office Buildings Sold'])&df['Date'].str.contains('|'.join(years))]
    df_HBU=df[df['Building Type'].isin(['Houses for Business Use Sold'])&df['Date'].str.contains('|'.join(years))] 

  #"#fd7f6f", "#7eb0d5", "#b2e061", "#bd7ebe"
  colors={'Commercialized Buildings Sold':'#fd7f6f',
          'Commercialized Residential Buildings Sold':'#7eb0d5',
          'Office Buildings Sold':'#b2e061',
          'Houses for Business Use Sold':'#bd7ebe'}

  #编辑hover显示的数据
  hover_text_CB=[]
  for index, row in df_CB.iterrows():
      hover_text_CB.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Total_Sale}(100 million yuan)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Total_Sale=row['Total Sale (100 million yuan)']

              ))
  hover_text_CRB=[]
  for index, row in df_CRB.iterrows():
      hover_text_CRB.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Total_Sale}(100 million yuan)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Total_Sale=row['Total Sale (100 million yuan)']

              ))
  hover_text_OB=[]
  for index, row in df_OB.iterrows():
      hover_text_OB.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Total_Sale}(100 million yuan)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Total_Sale=row['Total Sale (100 million yuan)']

              ))
  hover_text_HBU=[]
  for index, row in df_HBU.iterrows():
      hover_text_HBU.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Total_Sale}(100 million yuan)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Total_Sale=row['Total Sale (100 million yuan)']

              ))
  #开始画图
  trace_ts_1=go.Scatter(x=df_CB["Date"],y=df_CB["Total Sale (100 million yuan)"],name="Commercialized Buildings",text=hover_text_CB,hoverinfo="text",mode="lines",marker_color='#fd7f6f')
  trace_ts_2=go.Scatter(x=df_CRB["Date"],y=df_CRB["Total Sale (100 million yuan)"],name="Commercialized Residential Buildings",mode="lines",text=hover_text_CRB,hoverinfo="text",marker_color='#7eb0d5')
  trace_ts_3=go.Scatter(x=df_OB["Date"],y=df_OB["Total Sale (100 million yuan)"],name="Office Buildings",mode="lines",text=hover_text_OB,hoverinfo="text",marker_color='#b2e061')
  trace_ts_4=go.Scatter(x=df_HBU["Date"],y=df_HBU["Total Sale (100 million yuan)"],name="Houses for Business Use",mode="lines",text=hover_text_HBU,hoverinfo="text",marker_color='#bd7ebe')

  trace_ts=[trace_ts_1,trace_ts_2,trace_ts_3,trace_ts_4]
  layout = go.Layout(
      barmode='stack',
      #title_text="Total Sales of Different Buildings per Month",
      #title_font_color='#425066'
  )
  fig_ts=go.Figure(data=trace_ts,layout=layout)
  return fig_ts


#导入全国每月完工面积数据
df_f = pd.read_csv("../dataset/monthly/Floor_space_completed_monthly_country.csv")
df_f.head(10)
df_f.dropna(axis='index',how='any',inplace=True)
df_f.head()

#画完工面积堆叠图
def paint_fig_fs(years=['2019','2020','2021','2022']):
    #按年份&建筑类型筛选数据
  for y in years:
    df_CB_F=df_f[df_f['Building Type'].isin(['Real Estate Total'])&df_f['Date'].str.contains('|'.join(years))]
    df_CRB_F=df_f[df_f['Building Type'].isin(['Commercialized Residential'])&df_f['Date'].str.contains('|'.join(years))]
    df_OB_F=df_f[df_f['Building Type'].isin(['Office Buildings'])&df_f['Date'].str.contains('|'.join(years))]
    df_HBU_F=df_f[df_f['Building Type'].isin(['Houses for Business Use'])&df_f['Date'].str.contains('|'.join(years))]

  #编辑hover数据
  hover_text_CB_F=[]
  for index, row in df_CB_F.iterrows():
      hover_text_CB_F.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Floor_space}(10000 sq.m)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Floor_space=row['Floor Space Completed (10000 sq.m)']
              ))
  hover_text_CRB_F=[]
  for index, row in df_CRB_F.iterrows():
      hover_text_CRB_F.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Floor_space}(10000 sq.m)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Floor_space=row['Floor Space Completed (10000 sq.m)']

              ))
  hover_text_OB_F=[]
  for index, row in df_OB_F.iterrows():
      hover_text_OB_F.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Floor_space}(10000 sq.m)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Floor_space=row['Floor Space Completed (10000 sq.m)']

              ))
  hover_text_HBU_F=[]
  for index, row in df_HBU_F.iterrows():
      hover_text_HBU_F.append(('<b>{BuildingType}</b><br>'+
              '{Date}<br>'+
              '{Floor_space}(10000 sq.m)').format(
                  Date=row['Date'],
                  BuildingType=row['Building Type'],
                  Floor_space=row['Floor Space Completed (10000 sq.m)']

              ))
   #开始画图
  #trace_fs_1=go.Bar(x=df_CB_F["Date"],y=df_CB_F["Floor Space Completed (10000 sq.m)"],name="Real Estate Total",hovertext=hover_text_CB_F,marker_color='#fd7f6f')
  trace_fs_2=go.Bar(x=df_CRB_F["Date"],y=df_CRB_F["Floor Space Completed (10000 sq.m)"],name="Commercialized Residential Buildings",hovertext=hover_text_CRB_F,text=[],hoverinfo="text",marker_color='#7eb0d5')
  trace_fs_3=go.Bar(x=df_OB_F["Date"],y=df_OB_F["Floor Space Completed (10000 sq.m)"],name="Office Buildings",hovertext=hover_text_OB_F,text=[],hoverinfo="text",marker_color='#b2e061')
  trace_fs_4=go.Bar(x=df_HBU_F["Date"],y=df_HBU_F["Floor Space Completed (10000 sq.m)"],name="Houses for Business Use",hovertext=hover_text_HBU_F,text=[],hoverinfo="text",marker_color='#bd7ebe')

  trace_fs=[trace_fs_2,trace_fs_3,trace_fs_4]
  layout = go.Layout(
      
      barmode='stack',
      
      #title_text="Floor Space Completed of Different Buildings per Month",
      #title_font_color="#425066"
      legend=dict(
      orientation="h",
      yanchor="bottom",
      y=1.02,
      xanchor="center",
      x=0.5,
      title_text=''
  )

      
  )
  fig_fs=go.Figure(data=trace_fs,layout=layout)
  return fig_fs


#获取月度数据
def get_month_data(month='2022/08'):
  return df_f[df_f['Date'].str.contains(month)]

#画完工面积和销售面积比值的treemap
parent = ["", "", ""]
colors = [
        '#B0C4DE',
        '#B0C4DE',
        '#B0C4DE']
layout_tree = go.Layout(

        title_text="Ratio of Floor Space Completed to Floor Space Sold of Different Buildings per Month",
        title_font_color="#425066",

    )
def paint_fig_treemap():


    hover_text = []

    for index, row in get_month_data().iterrows():
        hover_text.append(('Month:{}<br>' +

                           'Proportion:<b>{:.2%}</b>').format(
            row['Date'],

            row['Proportion']

        ))
    trace_init = go.Treemap(
        labels=get_month_data()['Building Type'],
        parents=parent,
        values=get_month_data()['Proportion'],
        marker_colors=colors,

        text=hover_text,
        hoverinfo="text"
    )


    figtreemap = go.Figure(data=trace_init, layout=layout_tree)

    return figtreemap


#dashboard
#!pip install dash
#!pip install jupyter_dash


import dash_html_components as html
import dash_bootstrap_components as dbc
from dash import dcc, Input, Output
from dash import html
import pandas as pd
from jupyter_dash import JupyterDash
from dash.dependencies import Input, Output
import copy
import re


year_list=['2019','2020','2021','2022']


app = JupyterDash(external_stylesheets=[dbc.themes.SPACELAB])

app.layout = html.Div([
    dbc.Card([dbc.CardHeader("Total Sales of Different Buildings per Month"),
        dbc.CardBody(
            
            dbc.Row([
                
              dbc.Col([dbc.Row([dbc.Col(
                  dcc.RangeSlider(2019, 2022, step=None, marks={
        2019: '2019',
        2020: '2020',
        2021: '2021',
        2022: '2022',
        
    },value=[2019, 2022], id='year-range-slider')
                            #dbc.Checklist(
                                #id="YearChecklist",
                                #options=[{"label": e, "value": e} for e in year_list],
                                ##inline=True
                            #),
                        ),
                        dbc.Col()]),
                    
                    dcc.Graph(
        id='fig_ts',
        figure=paint_fig_ts())

              ],width=12)
                
            ]))]),
    dbc.Card([dbc.CardHeader("Floor Space Completed of Different Buildings per Month"),
        dbc.CardBody(
            
            dbc.Row(children=[
                
                dbc.Col(children=[
                    dbc.Row([dbc.Col(
                        dcc.RangeSlider(2019, 2022, step=None, marks={
        2019: '2019',
        2020: '2020',
        2021: '2021',
        2022: '2022',
        
    }, value=[2019, 2022],id='year-range-slider-fs')),dbc.Col()]
                            #dbc.Checklist(
                             #   id="YearChecklist_fs",
                              #  options=[{"label": e, "value": e} for e in year_list],
                               # inline=True
                            #),
                        ),
                    
                    dcc.Graph(
        id='fig_fs',
        figure=paint_fig_fs())],width=9

                ),
                dbc.Col(dcc.Graph(
        id='figtreemap',
        figure=paint_fig_treemap()),width=3)]
                
            ))]),
           
            
           
])
@app.callback(
    Output("fig_ts", "figure"),   
    Input("year-range-slider", "value")
        
    
)
def update_line_graph(years):
    years_new=[]
    if not years:
      return paint_fig_ts()
    else:
      for y in range(years[0],years[1]+1):
          years_new.append(str(y))
      
      return paint_fig_ts(years_new)

@app.callback(
    Output("fig_fs", "figure"),   
    Input("year-range-slider-fs", "value")
        
    
)
def update_bar_chart(years):
    years_new=[]
    if not years:
      return paint_fig_fs()
    else:
      for y in range(years[0],years[1]+1):
          years_new.append(str(y))
      
      return paint_fig_fs(years_new)


@app.callback(
    Output('figtreemap', 'figure'),
    Input('fig_fs', 'hoverData')
)
def linkTreemapBarChart(hoverData): 
    # make a copy of the bar chart and color
    updateTree = copy.deepcopy(paint_fig_treemap())
    updateColor = copy.deepcopy(colors)
    if hoverData is None:
      return updateTree
    else:
      hoverLabel = hoverData['points'][0]['label']
      data=get_month_data(hoverLabel)
      hover_info = hoverData['points'][0]['hovertext']
      buildingtype=re.search('<b>(.+?)</b>', hover_info).group(1)
      hover_text=[]
      for index, row in data.iterrows():
          hover_text.append(('Month:{}<br>'+
                  
                  'Proportion:<b>{:.2%}</b>').format(
                      row['Date'],
          
                      row['Proportion']

                  ))
      if (buildingtype == 'Commercialized Residential'):
        updateColor[0]='#4682B4'
      elif (buildingtype == 'Houses for Business Use'):
        updateColor[1]='#4682B4'
      else:
        updateColor[2]='#4682B4'

      trace=go.Treemap(  
          labels = data['Building Type'],
          parents = parent,
          values = data['Proportion'],
          marker_colors = updateColor,
          
          text=hover_text,
          hoverinfo="text"
      ) 
      layout = go.Layout(margin = dict(t=50, l=25, r=25, b=25))
      return (go.Figure(data=trace,layout=layout_tree))
    
 



# Run app and display result inline in the notebook
app.run_server(mode='external')
